### ISSUE TITLE
Async web controller method throws exception

### ISSUE THREAD

**Issue by roarfred** [IFRCGo/cbs#288]
### Description
I was struggling with some exceptions in the Admin project, and found that some of the API methods fails with a stach trace similar to this:

```
[23:26:27 ERR] Connection id "0HL8TG5D3I790", Request id "0HL8TG5D3I790:00000003": An unhandled exception was thrown by the application.
System.InvalidOperationException: Command not established
   at Infrastructure.AspNet.ControllerActionCommandContextManager.GetCurrent() in C:\Users\roarf\OneDrive\Documents\GitHub\roarfred\cbs\Source\Infrastructure\AspNet\doLittleModule.cs:line 73
   at Infrastructure.AspNet.CommandFilter.OnResultExecuted(ResultExecutedContext context) in C:\Users\roarf\OneDrive\Documents\GitHub\roarfred\cbs\Source\Infrastructure\AspNet\CommandFilter.cs:line 19
   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnResultExecutionAsync>d__9.MoveNext()
```
It turns out that this only happens for async methods, so if I change it to an async method it'll work.

**This works just fine:**
```
[HttpGet]
public IEnumerable<Project> Get()
{
    return _projects.GetAll();
}
```
**This throws an exception**
```
[HttpGet("asyncthrowsexception")]
public async Task<IEnumerable<Project>> GetAsyncThrowsException()
{
    return await _projects.GetAllASync();
}
```
Can't really figure out what's wrong. Maybe someone has a good explanation?

**Comment by einari** [comment]
The problem is in that the current CommandContext that gets established is being held in a `[ThreadStatic]` - but we need to be using `AsyncLocal<>` inside the `ControllerActionCommandContextManager`. But it needs to be a bit more clever, it needs to detect if the execution context from a controller is an async operation or not - if it is not, then it should use `ThreadLocal<>`.

The purpose of it is that you want to keep a "static" per controller request. 

The ideal solution is to solve this with the IOC container - in fact that might be easiest. Just need a bit of rewriting to do it. Then we could be using the `.AddScoped<ICommandContext>(() => new CommandContext...)` and take a dependency to the `ICommandContext`where its needed. 

All that being said; `ICommandContext` is actually being retired inside doLittle for a new mechanism. I'll see what I do with it - short term / long term consideration.

**Comment by roarfred** [comment]
Thanks! I'll just try to stick with sync controllers for now :)

**Comment by einari** [comment]
You can also use async operations in a synchronous controller action, just not await them by using the `await` keyword.  Depending on what you want to do, you could do a `ConfigureAwait`if you want (read more [here](https://msdn.microsoft.com/en-us/library/system.threading.tasks.task.configureawait%28v=vs.110%29.aspx)) or just do `ContinueWith` (read more [here](https://msdn.microsoft.com/en-us/library/system.threading.tasks.task.continuewith(v=vs.110).aspx)) if you have multiple things you want to do in a chain. 

It is also possible to pile up tasks and wait for them all (see [here](https://msdn.microsoft.com/en-us/library/dd270695(v=vs.110).aspx)). Or even use the `Parallel.Invoke()`method (see [here](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/how-to-use-parallel-invoke-to-execute-parallel-operations)). All the async/await stuff is just sugar on top of these things.

**Comment by roarfred** [comment]
Pretty sure this is related... Once I inherit AbstractValidator on my command class, the same exception is thrown. No asyncity on my side, but probably in the FluentValidator?

I'd appreciate a head's up if I'm totally off here :)

**Stack Trace**
```
[11:07:33 ERR] Connection id "0HL8UMINR2UE2", Request id "0HL8UMINR2UE2:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: Command not established
   at Infrastructure.AspNet.ControllerActionCommandContextManager.GetCurrent() in C:\Users\roarf\OneDrive\Documents\GitHub\roarfred\cbs\Source\Infrastructure\AspNet\doLittleModule.cs:line 73
   at Infrastructure.AspNet.CommandFilter.OnResultExecuted(ResultExecutedContext context) in C:\Users\roarf\OneDrive\Documents\GitHub\roarfred\cbs\Source\Infrastructure\AspNet\CommandFilter.cs:line 19
   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnResultExecutionAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResultFilterAsync>d__24.MoveNext()
```

**Comment by einari** [comment]
There is probably a relation. But, your command should never inherit from AbstractValidator, it should be in its own file - seperate concern. Or am I misunderstanding what you're doing?

**Comment by roarfred** [comment]
No, my bad, my mess! Fixed, but same exception, as might expected. Thanks for pointing this out tough!

**Comment by einari** [comment]
Ok. I'll have a look later tonight around this and put in a work around, since the change I'm working on is a bit bigger. 

Sorry for the trouble.

**Comment by einari** [comment]
Btw: your pull request - is it reproducing the problem as well?

**Comment by roarfred** [comment]
Not at the moment, the code is there, just commented out not to produce this error:
* [Validator Class](https://github.com/roarfred/cbs/blob/master/Source/Admin/Domain/SetProjectHealthRiskThresholdValidator.cs)
* [Async method in controller](https://github.com/roarfred/cbs/blob/master/Source/Admin/Web/ProjectController.cs#L39)
